[workspace]
resolver = "2"
members = ["crates/steel-core", "crates/steel-driver"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Dimitriy \"ay0ks\" <ay0o0ks000@gmail.com>"]

[workspace.dependencies]
tokio = { version = "1.38.0", features = ["full"] }
